export const default_language = [
    { name: "Afrikaans (South Africa)", code: "af-ZA" },
    // eslint-disable-next-line quotes
    { name: "Amharic (Ethiopia)", code: "am-ET" },
    { name: "Arabic (United Arab Emirates)", code: "ar-AE" },
    { name: "Arabic (Bahrain)", code: "ar-BH" },
    { name: "Arabic (Algeria)", code: "ar-DZ" },
    { name: "Arabic (Egypt)", code: "ar-EG" },
    { name: "Arabic (Iraq)", code: "ar-IQ" },
    { name: "Arabic (Jordan)", code: "ar-JO" },
    { name: "Arabic (Kuwait)", code: "ar-KW" },
    { name: "Arabic (Lebanon)", code: "ar-LB" },
    { name: "Arabic (Libya)", code: "ar-LY" },
    { name: "Arabic (Morocco)", code: "ar-MA" },
    { name: "Arabic (Oman)", code: "ar-OM" },
    { name: "Arabic (Qatar)", code: "ar-QA" },
    { name: "Arabic (Saudi Arabia)", code: "ar-SA" },
    { name: "Arabic (Syria)", code: "ar-SY" },
    { name: "Arabic (Tunisia)", code: "ar-TN" },
    { name: "Arabic (Yemen)", code: "ar-YE" },
    { name: "Assamese (India)", code: "as-IN" },
    { name: "Azerbaijani (Latin, Azerbaijan)", code: "az-AZ" },
    { name: "Bulgarian (Bulgaria)", code: "bg-BG" },
    { name: "Bangla (Bangladesh)", code: "bn-BD" },
    { name: "Bengali (India)", code: "bn-IN" },
    { name: "Bosnian (Bosnia and Herzegovina)", code: "bs-BA" },
    { name: "Catalan", code: "ca-ES" },
    { name: "Czech (Czechia)", code: "cs-CZ" },
    { name: "Welsh (United Kingdom)", code: "cy-GB" },
    { name: "Danish (Denmark)", code: "da-DK" },
    { name: "German (Austria)", code: "de-AT" },
    { name: "German (Switzerland)", code: "de-CH" },
    { name: "German (Germany)", code: "de-DE" },
    { name: "Greek (Greece)", code: "el-GR" },
    { name: "English (Australia)", code: "en-AU" },
    { name: "English (Canada)", code: "en-CA" },
    { name: "English (United Kingdom)", code: "en-GB" },
    { name: "English (Hong Kong SAR)", code: "en-HK" },
    { name: "English (Ireland)", code: "en-IE" },
    { name: "English (India)", code: "en-IN" },
    { name: "English (Kenya)", code: "en-KE" },
    { name: "English (Nigeria)", code: "en-NG" },
    { name: "English (New Zealand)", code: "en-NZ" },
    { name: "English (Philippines)", code: "en-PH" },
    { name: "English (Singapore)", code: "en-SG" },
    { name: "English (Tanzania)", code: "en-TZ" },
    { name: "English (United States)", code: "en-US" },
    { name: "English (South Africa)", code: "en-ZA" },
    { name: "Spanish (Argentina)", code: "es-AR" },
    { name: "Spanish (Bolivia)", code: "es-BO" },
    { name: "Spanish (Chile)", code: "es-CL" },
    { name: "Spanish (Colombia)", code: "es-CO" },
    { name: "Spanish (Costa Rica)", code: "es-CR" },
    { name: "Spanish (Cuba)", code: "es-CU" },
    { name: "Spanish (Dominican Republic)", code: "es-DO" },
    { name: "Spanish (Ecuador)", code: "es-EC" },
    { name: "Spanish (Spain)", code: "es-ES" },
    { name: "Spanish (Equatorial Guinea)", code: "es-GQ" },
    { name: "Spanish (Guatemala)", code: "es-GT" },
    { name: "Spanish (Honduras)", code: "es-HN" },
    { name: "Spanish (Mexico)", code: "es-MX" },
    { name: "Spanish (Nicaragua)", code: "es-NI" },
    { name: "Spanish (Panama)", code: "es-PA" },
    { name: "Spanish (Peru)", code: "es-PE" },
    { name: "Spanish (Puerto Rico)", code: "es-PR" },
    { name: "Spanish (Paraguay)", code: "es-PY" },
    { name: "Spanish (El Salvador)", code: "es-SV" },
    { name: "Spanish (United States)", code: "es-US" },
    { name: "Spanish (Uruguay)", code: "es-UY" },
    { name: "Spanish (Venezuela)", code: "es-VE" },
    { name: "Estonian (Estonia)", code: "et-EE" },
    { name: "Basque", code: "eu-ES" },
    { name: "Persian (Iran)", code: "fa-IR" },
    { name: "Finnish (Finland)", code: "fi-FI" },
    { name: "Filipino (Philippines)", code: "fil-PH" },
    { name: "French (Belgium)", code: "fr-BE" },
    { name: "French (Canada)", code: "fr-CA" },
    { name: "French (Switzerland)", code: "fr-CH" },
    { name: "French (France)", code: "fr-FR" },
    { name: "Irish (Ireland)", code: "ga-IE" },
    { name: "Galician", code: "gl-ES" },
    { name: "Gujarati (India)", code: "gu-IN" },
    { name: "Hebrew (Israel)", code: "he-IL" },
    { name: "Hindi (India)", code: "hi-IN" },
    { name: "Croatian (Croatia)", code: "hr-HR" },
    { name: "Hungarian (Hungary)", code: "hu-HU" },
    { name: "Armenian (Armenia)", code: "hy-AM" },
    { name: "Indonesian (Indonesia)", code: "id-ID" },
    { name: "Icelandic (Iceland)", code: "is-IS" },
    { name: "Italian (Italy)", code: "it-IT" },
    { name: "Japanese (Japan)", code: "ja-JP" },
    { name: "Javanese (Indonesia)", code: "jv-ID" },
    { name: "Georgian (Georgia)", code: "ka-GE" },
    { name: "Kazakh (Kazakhstan)", code: "kk-KZ" },
    { name: "Khmer (Cambodia)", code: "km-KH" },
    { name: "Kannada (India)", code: "kn-IN" },
    { name: "Korean (Korea)", code: "ko-KR" },
    { name: "Lao (Laos)", code: "lo-LA" },
    { name: "Lithuanian (Lithuania)", code: "lt-LT" },
    { name: "Latvian (Latvia)", code: "lv-LV" },
    { name: "Macedonian (North Macedonia)", code: "mk-MK" },
    { name: "Malayalam (India)", code: "ml-IN" },
    { name: "Mongolian (Mongolia)", code: "mn-MN" },
    { name: "Marathi (India)", code: "mr-IN" },
    { name: "Malay (Malaysia)", code: "ms-MY" },
    { name: "Maltese (Malta)", code: "mt-MT" },
    { name: "Burmese (Myanmar)", code: "my-MM" },
    { name: "Norwegian Bokmål (Norway)", code: "nb-NO" },
    { name: "Nepali (Nepal)", code: "ne-NP" },
    { name: "Dutch (Belgium)", code: "nl-BE" },
    { name: "Dutch (Netherlands)", code: "nl-NL" },
    { name: "Polish (Poland)", code: "pl-PL" },
    { name: "Pashto (Afghanistan)", code: "ps-AF" },
    { name: "Portuguese (Brazil)", code: "pt-BR" },
    { name: "Portuguese (Portugal)", code: "pt-PT" },
    { name: "Romanian (Romania)", code: "ro-RO" },
    { name: "Russian (Russia)", code: "ru-RU" },
    { name: "Sinhala (Sri Lanka)", code: "si-LK" },
    { name: "Slovak (Slovakia)", code: "sk-SK" },
    { name: "Slovenian (Slovenia)", code: "sl-SI" },
    { name: "Somali (Somalia)", code: "so-SO" },
    { name: "Albanian (Albania)", code: "sq-AL" },
    { name: "Serbian (Cyrillic, Serbia)", code: "sr-RS" },
    { name: "Swedish (Sweden)", code: "sv-SE" },
    { name: "Kiswahili (Kenya)", code: "sw-KE" },
    { name: "Tamil (India)", code: "ta-IN" },
    { name: "Telugu (India)", code: "te-IN" },
    { name: "Thai (Thailand)", code: "th-TH" },
    { name: "Turkish (Turkey)", code: "tr-TR" },
    { name: "Ukrainian (Ukraine)", code: "uk-UA" },
    { name: "Urdu (India)", code: "ur-IN" },
    { name: "Uzbek (Uzbekistan)", code: "uz-UZ" },
    { name: "Vietnamese (Vietnam)", code: "vi-VN" },
    { name: "Chinese (Mandarin, Simplified)", code: "zh-CN" },
    { name: "Chinese (Hong Kong)", code: "zh-HK" },
    { name: "Chinese (Taiwan)", code: "zh-TW" },
    { name: "isiZulu (South Africa)", code: "zu-ZA" }
  ];
  
  export const target_language = [
    { name: "Afrikaans", code: "af" },
    { name: "Albanian", code: "sq" },
    { name: "Amharic", code: "am" },
    { name: "Arabic", code: "ar" },
    { name: "Armenian", code: "hy" },
    { name: "Assamese", code: "as" },
    { name: "Azerbaijani", code: "az" },
    { name: "Bangla", code: "bn" },
    { name: "Bosnian (Latin)", code: "bs" },
    { name: "Bulgarian", code: "bg" },
    { name: "Cantonese (Traditional)", code: "yue" },
    { name: "Catalan", code: "ca" },
    { name: "Chinese (Literary)", code: "lzh" },
    { name: "Chinese Simplified", code: "zh-Hans" },
    { name: "Chinese Traditional", code: "zh-Hant" },
    { name: "Croatian", code: "hr" },
    { name: "Czech", code: "cs" },
    { name: "Danish", code: "da" },
    { name: "Dari", code: "prs" },
    { name: "Dutch", code: "nl" },
    { name: "English", code: "en" },
    { name: "Estonian", code: "et" },
    { name: "Fijian", code: "fj" },
    { name: "Filipino", code: "fil" },
    { name: "Finnish", code: "fi" },
    { name: "French", code: "fr" },
    { name: "French (Canada)", code: "fr-ca" },
    { name: "German", code: "de" },
    { name: "Greek", code: "el" },
    { name: "Gujarati", code: "gu" },
    { name: "Haitian Creole", code: "ht" },
    { name: "Hebrew", code: "he" },
    { name: "Hindi", code: "hi" },
    { name: "Hmong Daw", code: "mww" },
    { name: "Hungarian", code: "hu" },
    { name: "Icelandic", code: "is" },
    { name: "Indonesian", code: "id" },
    { name: "Inuktitut", code: "iu" },
    { name: "Irish", code: "ga" },
    { name: "Italian", code: "it" },
    { name: "Japanese", code: "ja" },
    { name: "Kannada", code: "kn" },
    { name: "Kazakh", code: "kk" },
    { name: "Khmer", code: "km" },
    { name: "Klingon", code: "tlh-Latn" },
    { name: "Klingon (plqaD)", code: "tlh-Piqd" },
    { name: "Korean", code: "ko" },
    { name: "Kurdish (Central)", code: "ku" },
    { name: "Kurdish (Northern)", code: "kmr" },
    { name: "Lao", code: "lo" },
    { name: "Latvian", code: "lv" },
    { name: "Lithuanian", code: "lt" },
    { name: "Malagasy", code: "mg" },
    { name: "Malay", code: "ms" },
    { name: "Malayalam", code: "ml" },
    { name: "Maltese", code: "mt" },
    { name: "Maori", code: "mi" },
    { name: "Marathi", code: "mr" },
    { name: "Myanmar", code: "my" },
    { name: "Nepali", code: "ne" },
    { name: "Norwegian", code: "nb" },
    { name: "Odia", code: "or" },
    { name: "Pashto", code: "ps" },
    { name: "Persian", code: "fa" },
    { name: "Polish", code: "pl" },
    { name: "Portuguese (Brazil)", code: "pt" },
    { name: "Portuguese (Portugal)", code: "pt-pt" },
    { name: "Punjabi", code: "pa" },
    { name: "Queretaro Otomi", code: "otq" },
    { name: "Romanian", code: "ro" },
    { name: "Russian", code: "ru" },
    { name: "Samoan", code: "sm" },
    { name: "Serbian (Cyrillic)", code: "sr-Cyrl" },
    { name: "Serbian (Latin)", code: "sr-Latn" },
    { name: "Slovak", code: "sk" },
    { name: "Slovenian", code: "sl" },
    { name: "Spanish", code: "es" },
    { name: "Swahili", code: "sw" },
    { name: "Swedish", code: "sv" },
    { name: "Tahitian", code: "ty" },
    { name: "Tamil", code: "ta" },
    { name: "Telugu", code: "te" },
    { name: "Thai", code: "th" },
    { name: "Tigrinya", code: "ti" },
    { name: "Tongan", code: "to" },
    { name: "Turkish", code: "tr" },
    { name: "Ukrainian", code: "uk" },
    { name: "Urdu", code: "ur" },
    { name: "Vietnamese", code: "vi" },
    { name: "Welsh", code: "cy" },
    { name: "Yucatec Maya", code: "yua" }
  ];
  